namespace Quartz.Entity
{
    using System.Collections.Generic;

    public partial class MetaData
    {
        public static Dictionary<string, string> Mapping = new Dictionary<string, string>
        {
            { "QuartzJobDetails.PrimaryKey", "sched_name" },
            { "QuartzJobDetails", "quartz_job_details" },
            { "QuartzJobDetails.SchedName", "sched_name" },
            { "QuartzJobDetails.JobName", "job_name" },
            { "QuartzJobDetails.JobGroup", "job_group" },
            { "QuartzJobDetails.Description", "description" },
            { "QuartzJobDetails.JobClassName", "job_class_name" },
            { "QuartzJobDetails.IsDurable", "is_durable" },
            { "QuartzJobDetails.IsNonconcurrent", "is_nonconcurrent" },
            { "QuartzJobDetails.IsUpdateData", "is_update_data" },
            { "QuartzJobDetails.RequestsRecovery", "requests_recovery" },
            { "QuartzJobDetails.JobData", "job_data" },

            { "QuartzTriggers.PrimaryKey", "sched_name" },
            { "QuartzTriggers", "quartz_triggers" },
            { "QuartzTriggers.SchedName", "sched_name" },
            { "QuartzTriggers.TriggerName", "trigger_name" },
            { "QuartzTriggers.TriggerGroup", "trigger_group" },
            { "QuartzTriggers.JobName", "job_name" },
            { "QuartzTriggers.JobGroup", "job_group" },
            { "QuartzTriggers.Description", "description" },
            { "QuartzTriggers.NextFireTime", "next_fire_time" },
            { "QuartzTriggers.PrevFireTime", "prev_fire_time" },
            { "QuartzTriggers.Priority", "priority" },
            { "QuartzTriggers.TriggerState", "trigger_state" },
            { "QuartzTriggers.TriggerType", "trigger_type" },
            { "QuartzTriggers.StartTime", "start_time" },
            { "QuartzTriggers.EndTime", "end_time" },
            { "QuartzTriggers.CalendarName", "calendar_name" },
            { "QuartzTriggers.MisfireInstr", "misfire_instr" },
            { "QuartzTriggers.JobData", "job_data" },

            { "QuartzSimpleTriggers.PrimaryKey", "sched_name" },
            { "QuartzSimpleTriggers", "quartz_simple_triggers" },
            { "QuartzSimpleTriggers.SchedName", "sched_name" },
            { "QuartzSimpleTriggers.TriggerName", "trigger_name" },
            { "QuartzSimpleTriggers.TriggerGroup", "trigger_group" },
            { "QuartzSimpleTriggers.RepeatCount", "repeat_count" },
            { "QuartzSimpleTriggers.RepeatInterval", "repeat_interval" },
            { "QuartzSimpleTriggers.TimesTriggered", "times_triggered" },

            { "QuartzSimpropTriggers.PrimaryKey", "sched_name" },
            { "QuartzSimpropTriggers", "quartz_simprop_triggers" },
            { "QuartzSimpropTriggers.SchedName", "sched_name" },
            { "QuartzSimpropTriggers.TriggerName", "trigger_name" },
            { "QuartzSimpropTriggers.TriggerGroup", "trigger_group" },
            { "QuartzSimpropTriggers.StrProp1", "str_prop_1" },
            { "QuartzSimpropTriggers.StrProp2", "str_prop_2" },
            { "QuartzSimpropTriggers.StrProp3", "str_prop_3" },
            { "QuartzSimpropTriggers.IntProp1", "int_prop_1" },
            { "QuartzSimpropTriggers.IntProp2", "int_prop_2" },
            { "QuartzSimpropTriggers.LongProp1", "long_prop_1" },
            { "QuartzSimpropTriggers.LongProp2", "long_prop_2" },
            { "QuartzSimpropTriggers.DecProp1", "dec_prop_1" },
            { "QuartzSimpropTriggers.DecProp2", "dec_prop_2" },
            { "QuartzSimpropTriggers.BoolProp1", "bool_prop_1" },
            { "QuartzSimpropTriggers.BoolProp2", "bool_prop_2" },
            { "QuartzSimpropTriggers.TimeZoneId", "time_zone_id" },

            { "QuartzCronTriggers.PrimaryKey", "sched_name" },
            { "QuartzCronTriggers", "quartz_cron_triggers" },
            { "QuartzCronTriggers.SchedName", "sched_name" },
            { "QuartzCronTriggers.TriggerName", "trigger_name" },
            { "QuartzCronTriggers.TriggerGroup", "trigger_group" },
            { "QuartzCronTriggers.CronExpression", "cron_expression" },
            { "QuartzCronTriggers.TimeZoneId", "time_zone_id" },

            { "QuartzBlobTriggers.PrimaryKey", "sched_name" },
            { "QuartzBlobTriggers", "quartz_blob_triggers" },
            { "QuartzBlobTriggers.SchedName", "sched_name" },
            { "QuartzBlobTriggers.TriggerName", "trigger_name" },
            { "QuartzBlobTriggers.TriggerGroup", "trigger_group" },
            { "QuartzBlobTriggers.BlobData", "blob_data" },

            { "QuartzCalendars.PrimaryKey", "sched_name" },
            { "QuartzCalendars", "quartz_calendars" },
            { "QuartzCalendars.SchedName", "sched_name" },
            { "QuartzCalendars.CalendarName", "calendar_name" },
            { "QuartzCalendars.Calendar", "calendar" },

            { "QuartzPausedTriggerGrps.PrimaryKey", "sched_name" },
            { "QuartzPausedTriggerGrps", "quartz_paused_trigger_grps" },
            { "QuartzPausedTriggerGrps.SchedName", "sched_name" },
            { "QuartzPausedTriggerGrps.TriggerGroup", "trigger_group" },

            { "QuartzFiredTriggers.PrimaryKey", "sched_name" },
            { "QuartzFiredTriggers", "quartz_fired_triggers" },
            { "QuartzFiredTriggers.SchedName", "sched_name" },
            { "QuartzFiredTriggers.EntryId", "entry_id" },
            { "QuartzFiredTriggers.TriggerName", "trigger_name" },
            { "QuartzFiredTriggers.TriggerGroup", "trigger_group" },
            { "QuartzFiredTriggers.InstanceName", "instance_name" },
            { "QuartzFiredTriggers.FiredTime", "fired_time" },
            { "QuartzFiredTriggers.SchedTime", "sched_time" },
            { "QuartzFiredTriggers.Priority", "priority" },
            { "QuartzFiredTriggers.State", "state" },
            { "QuartzFiredTriggers.JobName", "job_name" },
            { "QuartzFiredTriggers.JobGroup", "job_group" },
            { "QuartzFiredTriggers.IsNonconcurrent", "is_nonconcurrent" },
            { "QuartzFiredTriggers.RequestsRecovery", "requests_recovery" },

            { "QuartzSchedulerState.PrimaryKey", "sched_name" },
            { "QuartzSchedulerState", "quartz_scheduler_state" },
            { "QuartzSchedulerState.SchedName", "sched_name" },
            { "QuartzSchedulerState.InstanceName", "instance_name" },
            { "QuartzSchedulerState.LastCheckinTime", "last_checkin_time" },
            { "QuartzSchedulerState.CheckinInterval", "checkin_interval" },

            { "QuartzLocks.PrimaryKey", "sched_name" },
            { "QuartzLocks", "quartz_locks" },
            { "QuartzLocks.SchedName", "sched_name" },
            { "QuartzLocks.LockName", "lock_name" },

            { "Icon.PrimaryKey", "id" },
            { "Icon", "Icon" },
            { "Icon.Id", "id" },
            { "Icon.Name", "name" },
            { "Icon.Sort", "sort" },

            { "QuartzLog.PrimaryKey", "id" },
            { "QuartzLog", "quartz_log" },
            { "QuartzLog.Id", "id" },
            { "QuartzLog.Name", "name" },
            { "QuartzLog.Group", "group" },
            { "QuartzLog.Message", "message" },
            { "QuartzLog.LogLevel", "log_level" },
            { "QuartzLog.ExcuteTime", "excute_time" },
            { "QuartzLog.CreateTime", "create_time" },
        };
    }
}
